version: '3.7'
services:
  app:
    image: nginx
    container_name: frontend-app
    volumes:
      - ./frontends:/usr/share/nginx/html
    ports:
      - '80:80'
    networks:
      - admission-bot

  rasa:
    container_name: "rasa"
    user: root
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./:/app
    networks:
      - admission-bot
    ports:
      - 5005:5005
    depends_on:
      - app
      - postgres

  rasa-action_server:
    build:
      context: .
      dockerfile: ./actions/Dockerfile
    image: rasa-action_server
    container_name: rasa-action_server
    working_dir: /app
    command:
      - start
      - --debug
      - --actions
      - actions
      - --cors
      - "*"
    volumes:
      - ./actions:/app/actions
      - ./data:/app/data
    networks:
      - admission-bot
    ports:
      - 5055:5055
    depends_on:
      - rasa
    expose:
      - 5055

  postgres:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "MEShe19682002."
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_DB: rasa
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - admission-bot

volumes:
  db-data: {}

networks:
  admission-bot:
    name: admission-bot
    driver: bridge
